version: '3.4'

services:
  gatekeeper:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DISCORD_SECRET: test
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
