version: '3.4'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gatekeeper
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresqldata

  gatekeeper:
    container_name: gatekeeper
    image: ${DOCKER_REGISTRY-}gatekeeper
    build:
      context: .
      dockerfile: Gatekeeper/Dockerfile
    environment:
      DB_CONN_STR: User ID=gatekeeper;Password=password;Host=db;Port=5432;Database=gatekeeper
      DISCORD_SECRET: 
    depends_on:
      - db

volumes:
  pgdata: